# Generated by Django 5.0.7 on 2024-07-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_group_options_alter_group_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Kontakt ', 'verbose_name_plural': 'Kontaktlar'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Guruh ', 'verbose_name_plural': 'Guruhlar'},
        ),
    ]
