# Generated by Django 5.0.7 on 2024-07-31 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='backend_dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backend_groups', to='contact.contact'),
        ),
        migrations.AlterField(
            model_name='group',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_groups', to='contact.contact'),
        ),
        migrations.AlterField(
            model_name='group',
            name='frontend_dev2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_dev2_groups', to='contact.contact'),
        ),
    ]
