# Generated by Django 5.0.7 on 2024-07-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_group_backend_dev_alter_group_designer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='frontend_dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_dev_groups', to='contact.contact'),
        ),
    ]
